trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'FW Variables'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(subscriptionId)'
    scriptLocation: 'inlineScript'
    scriptType: bash
    inlineScript: |
      az account set --subscription $(subscriptionId)
      az group create --name $(resourceGroup) --location $(location)
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(subscriptionId)'
    scriptLocation: 'inlineScript'
    scriptType: bash
    inlineScript: |
      az deployment group create --resource-group $(resourceGroup) --template-file main.bicep --parameters vnetName=vnet-hub hubName=hub spokeName=spoke001 adminPassword=$(Password)
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(subscriptionId)'
    scriptLocation: 'inlineScript'
    scriptType: bash
    inlineScript: |
      az deployment group create --resource-group $(resourceGroup) --template-file deploy.bicep --parameters vnetName=$(vnetName) firewallName=$(firewallName)
